<?php

namespace App\Services;

use App\Models\DailyReport;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\Shared\Date as ExcelDate;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use RuntimeException;
use Throwable;

class DailyVisitorReportService
{
    public const REPORT_TYPE = DailyReport::TYPE_DAILY_VISITOR;

    public const DATE_RANGE_REPORT_TYPE = DailyReport::TYPE_DATE_RANGE;

    public const DISK = 'local';

    /**
     * Generate (or regenerate) the daily visitor Excel report for a calendar date.
     *
     * @param  string|\DateTimeInterface  $date  YYYY-MM-DD or date object (Asia/Manila calendar day)
     * @param  int|null  $generatedByUserId  Null when generated by scheduler/system
     * @param  bool  $regenerate  Replace an existing completed report
     */
    public function generate(string|\DateTimeInterface $date, ?int $generatedByUserId = null, bool $regenerate = false): DailyReport
    {
        $reportDate = $this->normalizeReportDate($date);
        $dateString = $reportDate->toDateString();
        $fileName = $this->buildFileName($dateString);
        $relativePath = $this->buildRelativePath($dateString, $fileName);

        $report = DailyReport::query()->firstOrNew([
            'report_date' => $dateString,
            'report_type' => self::REPORT_TYPE,
        ]);

        if (
            $report->exists
            && $report->generation_status === DailyReport::STATUS_COMPLETED
            && ! $regenerate
        ) {
            Log::info('Daily visitor report already exists; skipping duplicate generation.', [
                'report_date' => $dateString,
                'report_id' => $report->id,
                'action' => 'daily_report_duplicate_skipped',
            ]);

            return $report;
        }

        if ($report->exists && $report->generation_status === DailyReport::STATUS_GENERATING) {
            throw new RuntimeException('A report for this date is already being generated. Please wait and try again.');
        }

        $previousPath = $report->exists ? (string) $report->file_path : null;

        $report->fill([
            'date_range_end' => null,
            'file_name' => $fileName,
            'file_path' => $relativePath,
            'generation_status' => DailyReport::STATUS_GENERATING,
            'error_message' => null,
            'generated_by' => $generatedByUserId,
        ]);
        $report->save();

        try {
            $rows = $this->fetchVisitorRowsForDate($reportDate);
            $absolutePath = $this->writeExcelFile($reportDate, $rows, $relativePath);

            if (! is_file($absolutePath)) {
                throw new RuntimeException('The Excel report file could not be saved to secure storage.');
            }

            // Safely replace previous file when regenerating to a different path.
            if ($previousPath && $previousPath !== $relativePath && Storage::disk(self::DISK)->exists($previousPath)) {
                Storage::disk(self::DISK)->delete($previousPath);
            }

            $report->fill([
                'file_name' => $fileName,
                'file_path' => $relativePath,
                'record_count' => $rows->count(),
                'generation_status' => DailyReport::STATUS_COMPLETED,
                'generated_at' => now('Asia/Manila'),
                'generated_by' => $generatedByUserId,
                'error_message' => null,
            ]);
            $report->save();

            $action = $regenerate ? 'daily_report_regenerated' : (
                $generatedByUserId ? 'daily_report_manually_generated' : 'daily_report_automatically_generated'
            );

            Log::info('Daily visitor report generated successfully.', [
                'action' => $action,
                'report_id' => $report->id,
                'report_date' => $dateString,
                'record_count' => $report->record_count,
                'file_name' => $fileName,
                'user_id' => $generatedByUserId,
            ]);

            return $report->fresh();
        } catch (Throwable $e) {
            $report->fill([
                'generation_status' => DailyReport::STATUS_FAILED,
                'error_message' => $this->safeErrorMessage($e),
                'generated_by' => $generatedByUserId,
            ]);
            $report->save();

            Log::error('Daily visitor report generation failed.', [
                'action' => 'daily_report_generation_failed',
                'report_id' => $report->id,
                'report_date' => $dateString,
                'user_id' => $generatedByUserId,
                'error' => $e->getMessage(),
            ]);

            throw $e;
        }
    }

    /**
     * Generate a manual multi-day visitor Excel report (6:00 AM–11:59:59 PM per day).
     *
     * @param  string|\DateTimeInterface  $startDate
     * @param  string|\DateTimeInterface  $endDate
     * @param  User|int|null  $adminUser  Admin user model or user id
     */
    public function generateDateRangeReport(
        string|\DateTimeInterface $startDate,
        string|\DateTimeInterface $endDate,
        User|int|null $adminUser = null
    ): DailyReport {
        [$start, $end] = $this->normalizeDateRange($startDate, $endDate);

        $startString = $start->toDateString();
        $endString = $end->toDateString();
        $fileName = $this->buildDateRangeFileName($startString, $endString);
        $relativePath = $this->buildDateRangeRelativePath($startString, $fileName);

        $generatedByUserId = $adminUser instanceof User
            ? (int) $adminUser->getAuthIdentifier()
            : ($adminUser !== null ? (int) $adminUser : null);

        $generatedByName = $this->resolveAdminDisplayName($adminUser);

        $report = new DailyReport([
            'report_date' => $startString,
            'date_range_end' => $endString,
            'report_type' => self::DATE_RANGE_REPORT_TYPE,
            'file_name' => $fileName,
            'file_path' => $relativePath,
            'generation_status' => DailyReport::STATUS_GENERATING,
            'generated_by' => $generatedByUserId,
            'error_message' => null,
        ]);
        $report->save();

        try {
            $rows = $this->fetchVisitorRowsForDateRange($start, $end);
            $absolutePath = $this->writeDateRangeExcelFile(
                $start,
                $end,
                $rows,
                $relativePath,
                $generatedByName
            );

            if (! is_file($absolutePath)) {
                throw new RuntimeException('The Excel report file could not be saved to secure storage.');
            }

            $report->fill([
                'file_name' => $fileName,
                'file_path' => $relativePath,
                'record_count' => $rows->count(),
                'generation_status' => DailyReport::STATUS_COMPLETED,
                'generated_at' => now('Asia/Manila'),
                'generated_by' => $generatedByUserId,
                'error_message' => null,
            ]);
            $report->save();

            Log::info('Date-range visitor report generated successfully.', [
                'action' => 'date_range_report_generated',
                'report_id' => $report->id,
                'start_date' => $startString,
                'end_date' => $endString,
                'record_count' => $report->record_count,
                'file_name' => $fileName,
                'user_id' => $generatedByUserId,
                'generation_status' => DailyReport::STATUS_COMPLETED,
            ]);

            return $report->fresh();
        } catch (Throwable $e) {
            $report->fill([
                'generation_status' => DailyReport::STATUS_FAILED,
                'error_message' => $this->safeErrorMessage($e),
                'generated_by' => $generatedByUserId,
            ]);
            $report->save();

            Log::error('Date-range visitor report generation failed.', [
                'action' => 'date_range_report_generation_failed',
                'report_id' => $report->id,
                'start_date' => $startString,
                'end_date' => $endString,
                'user_id' => $generatedByUserId,
                'generation_status' => DailyReport::STATUS_FAILED,
                'error' => $e->getMessage(),
            ]);

            throw $e;
        }
    }

    public function normalizeReportDate(string|\DateTimeInterface $date): Carbon
    {
        try {
            if ($date instanceof \DateTimeInterface) {
                $reportDate = Carbon::instance(\DateTimeImmutable::createFromInterface($date))
                    ->timezone('Asia/Manila')
                    ->startOfDay();
            } else {
                $raw = trim((string) $date);
                $parsed = Carbon::createFromFormat('Y-m-d', $raw, 'Asia/Manila');

                if (! $parsed || $parsed->format('Y-m-d') !== $raw) {
                    throw new RuntimeException('Invalid report date. Please use the YYYY-MM-DD format.');
                }

                $reportDate = $parsed->startOfDay();
            }
        } catch (RuntimeException $e) {
            throw $e;
        } catch (Throwable $e) {
            throw new RuntimeException('Invalid report date. Please use the YYYY-MM-DD format.');
        }

        $today = Carbon::now('Asia/Manila')->startOfDay();

        if ($reportDate->greaterThan($today)) {
            throw new RuntimeException('Future dates are not allowed for daily visitor reports.');
        }

        return $reportDate;
    }

    /**
     * Validate and normalize a manual date-range selection (Asia/Manila).
     *
     * @return array{0: Carbon, 1: Carbon}
     */
    public function normalizeDateRange(string|\DateTimeInterface $startDate, string|\DateTimeInterface $endDate): array
    {
        $start = $this->parseCalendarDate($startDate, 'start date');
        $end = $this->parseCalendarDate($endDate, 'end date');
        $today = Carbon::now('Asia/Manila')->startOfDay();

        if ($start->greaterThan($today) || $end->greaterThan($today)) {
            throw new RuntimeException('Future dates are not allowed.');
        }

        if ($end->lt($start)) {
            throw new RuntimeException('The end date must be on or after the start date.');
        }

        $inclusiveDays = $start->diffInDays($end) + 1;
        $maxDays = (int) config('reports.max_range_days', 31);

        if ($inclusiveDays < 2) {
            throw new RuntimeException('The selected range must cover at least two days.');
        }

        if ($inclusiveDays > $maxDays) {
            throw new RuntimeException('The selected date range cannot exceed '.$maxDays.' days.');
        }

        return [$start, $end];
    }

    public function buildFileName(string $dateString): string
    {
        return 'NU-Secure_Visitor_Report_'.$this->sanitizeDateToken($dateString).'.xlsx';
    }

    public function buildDateRangeFileName(string $startDate, string $endDate): string
    {
        return 'NU-Secure_Visitor_Report_'
            .$this->sanitizeDateToken($startDate)
            .'_to_'
            .$this->sanitizeDateToken($endDate)
            .'.xlsx';
    }

    public function buildRelativePath(string $dateString, string $fileName): string
    {
        $safeName = $this->sanitizeFileName($fileName);
        $parts = explode('-', $this->sanitizeDateToken($dateString));
        $year = $parts[0] ?? date('Y');
        $month = $parts[1] ?? date('m');

        return 'reports/daily/'.$year.'/'.$month.'/'.$safeName;
    }

    public function buildDateRangeRelativePath(string $startDate, string $fileName): string
    {
        $safeName = $this->sanitizeFileName($fileName);
        $parts = explode('-', $this->sanitizeDateToken($startDate));
        $year = $parts[0] ?? date('Y');
        $month = $parts[1] ?? date('m');

        return 'reports/date-range/'.$year.'/'.$month.'/'.$safeName;
    }

    /**
     * Calendar-day fetch used by the automated / manual daily report (00:00–23:59:59).
     *
     * @return Collection<int, array<string, mixed>>
     */
    public function fetchVisitorRowsForDate(Carbon $reportDate): Collection
    {
        $start = $reportDate->copy()->timezone('Asia/Manila')->startOfDay();
        $end = $reportDate->copy()->timezone('Asia/Manila')->endOfDay();

        return $this->fetchVisitorRowsUsingWindows([
            [$start->toDateTimeString(), $end->toDateTimeString()],
        ]);
    }

    /**
     * Multi-day fetch applying 6:00 AM–11:59:59 PM independently for every selected date.
     *
     * Does not use one continuous midnight-to-midnight range, so early-morning
     * records on the second and succeeding dates are excluded.
     *
     * @return Collection<int, array<string, mixed>>
     */
    public function fetchVisitorRowsForDateRange(Carbon $startDate, Carbon $endDate): Collection
    {
        return $this->fetchVisitorRowsUsingWindows(
            $this->buildOperatingDayWindows($startDate, $endDate)
        );
    }

    /**
     * Build per-day operating windows of 6:00:00 AM–11:59:59 PM (Asia/Manila).
     *
     * @return list<array{0: string, 1: string}>
     */
    public function buildOperatingDayWindows(Carbon $startDate, Carbon $endDate): array
    {
        $start = $startDate->copy()->timezone('Asia/Manila')->startOfDay();
        $end = $endDate->copy()->timezone('Asia/Manila')->startOfDay();

        if ($end->lt($start)) {
            throw new RuntimeException('The end date must be on or after the start date.');
        }

        $hour = (int) config('reports.operating_hour_start', 6);
        $minute = (int) config('reports.operating_minute_start', 0);
        $second = (int) config('reports.operating_second_start', 0);

        $windows = [];
        $cursor = $start->copy();

        while ($cursor->lte($end)) {
            $dayStart = $cursor->copy()->setTime($hour, $minute, $second);
            $dayEnd = $cursor->copy()->setTime(23, 59, 59);
            $windows[] = [$dayStart->toDateTimeString(), $dayEnd->toDateTimeString()];
            $cursor->addDay();
        }

        return $windows;
    }

    /**
     * Build spreadsheet content for the given rows (public for unit testing).
     *
     * @param  Collection<int, array<string, mixed>>  $rows
     */
    public function buildSpreadsheet(Carbon $reportDate, Collection $rows): Spreadsheet
    {
        $spreadsheet = new Spreadsheet;
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Daily Visitors');

        $lastColumn = 'S';

        $sheet->setCellValue('A1', 'NU-Secure Daily Visitor Report');
        $sheet->mergeCells('A1:'.$lastColumn.'1');
        $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(16);
        $sheet->getStyle('A1')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

        $sheet->setCellValue('A2', 'Report Date: '.$reportDate->format('F j, Y'));
        $sheet->mergeCells('A2:'.$lastColumn.'2');
        $sheet->getStyle('A2')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

        $this->writeVisitorTable($sheet, $rows, 4, $lastColumn);

        return $spreadsheet;
    }

    /**
     * Build a date-range workbook with operating-hours metadata.
     *
     * @param  Collection<int, array<string, mixed>>  $rows
     */
    public function buildDateRangeSpreadsheet(
        Carbon $startDate,
        Carbon $endDate,
        Collection $rows,
        string $generatedByName = '',
        ?Carbon $generatedAt = null
    ): Spreadsheet {
        $spreadsheet = new Spreadsheet;
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Date-Range Visitors');

        $lastColumn = 'S';
        $generatedAt = $generatedAt?->copy()->timezone('Asia/Manila') ?? now('Asia/Manila');

        $sheet->setCellValue('A1', 'NU-Secure Visitor Date-Range Report');
        $sheet->mergeCells('A1:'.$lastColumn.'1');
        $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(16);
        $sheet->getStyle('A1')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

        $meta = [
            2 => 'Start Date: '.$startDate->format('F j, Y'),
            3 => 'End Date: '.$endDate->format('F j, Y'),
            4 => 'Reporting Schedule: 6:00 AM to 11:59 PM per day',
            5 => 'Generated At: '.$generatedAt->format('F j, Y g:i:s A').' (Asia/Manila)',
            6 => 'Generated By: '.($generatedByName !== '' ? $generatedByName : 'Admin'),
        ];

        foreach ($meta as $row => $label) {
            $sheet->setCellValue('A'.$row, $label);
            $sheet->mergeCells('A'.$row.':'.$lastColumn.$row);
            $sheet->getStyle('A'.$row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
        }

        $this->writeVisitorTable($sheet, $rows, 8, $lastColumn);

        return $spreadsheet;
    }

    public function absoluteStoragePath(string $relativePath): string
    {
        return Storage::disk(self::DISK)->path($relativePath);
    }

    /**
     * @param  list<array{0: string, 1: string}>  $windows
     * @return Collection<int, array<string, mixed>>
     */
    protected function fetchVisitorRowsUsingWindows(array $windows): Collection
    {
        if ($windows === []) {
            return collect();
        }

        $query = DB::table('visit as v')
            ->leftJoin('visitor as vr', 'vr.visitor_id', '=', 'v.visitor_id')
            ->leftJoin('address as a', 'a.address_id', '=', 'vr.address_id')
            ->leftJoin('visit_type as vt', 'vt.visit_type_id', '=', 'v.visit_type_id')
            ->leftJoin('office as o', 'o.office_id', '=', 'v.primary_office_id')
            ->leftJoin('exit_status as es', 'es.exit_status_id', '=', 'v.exit_status_id')
            ->leftJoin('users as gu', 'gu.user_id', '=', 'v.guard_user_id')
            ->leftJoin('contractor as c', 'c.visit_id', '=', 'v.visit_id')
            ->whereNotNull('v.entry_time')
            ->where(function ($builder) use ($windows) {
                foreach ($windows as [$windowStart, $windowEnd]) {
                    $builder->orWhereBetween('v.entry_time', [$windowStart, $windowEnd]);
                }
            })
            ->orderBy('v.entry_time')
            ->orderBy('v.visit_id')
            ->select([
                'v.visit_id',
                'v.purpose_reason',
                'v.entry_time',
                'v.exit_time',
                'v.duration_minutes',
                'v.exit_status_id',
                'v.destination_text',
                'v.visit_type_id',
                'vr.control_number',
                'vr.first_name',
                'vr.last_name',
                'vr.birthday',
                'vr.contact_no',
                'vr.pass_number',
                'a.house_no',
                'a.street',
                'a.barangay',
                'a.city_municipality',
                'a.province',
                'a.region',
                'vt.visit_type_name',
                'o.office_name',
                'es.exit_status_name',
                'gu.first_name as guard_first_name',
                'gu.last_name as guard_last_name',
                'gu.role_id as guard_role_id',
                'c.contact_person as contractor_contact_person',
            ]);

        $visits = $query->get();

        return $this->mapVisitRows($visits);
    }

    /**
     * @param  Collection<int, object>|iterable<int, object>  $visits
     * @return Collection<int, array<string, mixed>>
     */
    protected function mapVisitRows(iterable $visits): Collection
    {
        $visits = collect($visits);
        $remarksByVisit = collect();
        $alertsByVisit = collect();
        $visitIds = $visits->pluck('visit_id')->filter()->values();

        if ($visitIds->isNotEmpty()) {
            $remarksByVisit = DB::table('office_scan')
                ->select(['visit_id', 'remarks', 'scan_time'])
                ->whereIn('visit_id', $visitIds)
                ->whereNotNull('remarks')
                ->whereRaw("TRIM(COALESCE(remarks, '')) <> ''")
                ->orderByDesc('scan_time')
                ->get()
                ->groupBy('visit_id')
                ->map(function ($group) {
                    return trim((string) ($group->first()->remarks ?? ''));
                });

            $alertsByVisit = DB::table('alerts')
                ->select(['visit_id', 'alert_type', 'created_at'])
                ->whereIn('visit_id', $visitIds)
                ->orderByDesc('created_at')
                ->get()
                ->groupBy('visit_id')
                ->map(function ($group) {
                    return trim((string) ($group->first()->alert_type ?? ''));
                });
        }

        return $visits->map(function ($row) use ($remarksByVisit, $alertsByVisit) {
            $visit = (array) $row;
            $visitId = $visit['visit_id'] ?? null;

            $firstName = trim((string) ($visit['first_name'] ?? ''));
            $lastName = trim((string) ($visit['last_name'] ?? ''));
            $fullName = trim($firstName.' '.$lastName);

            $entry = $this->parseDateTime($visit['entry_time'] ?? null);
            $exit = $this->parseDateTime($visit['exit_time'] ?? null);
            $birthday = $this->parseDateOnly($visit['birthday'] ?? null);
            $durationMinutes = $this->resolveDurationMinutes($visit, $entry, $exit);

            $officeOrPerson = $this->resolveOfficeOrPerson($visit);
            $status = $this->resolveVisitStatus($visit);
            $entryMethod = $this->resolveEntryMethod($visit);
            $processedBy = trim(((string) ($visit['guard_first_name'] ?? '')).' '.((string) ($visit['guard_last_name'] ?? '')));
            $remarks = (string) ($remarksByVisit->get($visitId, ''));
            $alertType = trim((string) ($alertsByVisit->get($visitId, '')));

            return [
                'visit_id' => $visitId !== null ? (string) $visitId : '',
                'control_number' => (string) ($visit['control_number'] ?? ''),
                'visitor_full_name' => $fullName,
                'birth_date' => $birthday,
                'address' => $this->formatAddress($visit),
                'contact_number' => (string) ($visit['contact_no'] ?? ''),
                'pass_number' => (string) ($visit['pass_number'] ?? ''),
                'visit_type' => (string) ($visit['visit_type_name'] ?? ''),
                'purpose_of_visit' => (string) ($visit['purpose_reason'] ?? ''),
                'office_or_person' => $officeOrPerson,
                'date_of_visit' => $entry ? $entry->copy()->startOfDay() : null,
                'time_in' => $entry,
                'time_out' => $exit,
                'duration' => $this->formatDurationLabel($durationMinutes),
                'visit_status' => $status,
                'entry_method' => $entryMethod,
                'processed_by' => $processedBy,
                'alert' => $alertType !== '' ? $alertType : 'None',
                'remarks' => $remarks,
            ];
        })->values();
    }

    /**
     * @param  Collection<int, array<string, mixed>>  $rows
     */
    protected function writeVisitorTable(Worksheet $sheet, Collection $rows, int $headerRow, string $lastColumn): void
    {
        $headers = [
            'A' => 'Visit ID',
            'B' => 'Control Number',
            'C' => 'Visitor Full Name',
            'D' => 'Birth Date',
            'E' => 'Address',
            'F' => 'Contact Number',
            'G' => 'Pass No.',
            'H' => 'Visit Type',
            'I' => 'Purpose of Visit',
            'J' => 'Office or Person to Visit',
            'K' => 'Date of Visit',
            'L' => 'Time In',
            'M' => 'Time Out',
            'N' => 'Duration',
            'O' => 'Visit Status',
            'P' => 'Entry Method',
            'Q' => 'Processed By',
            'R' => 'Alert',
            'S' => 'Remarks',
        ];

        foreach ($headers as $column => $label) {
            $sheet->setCellValue($column.$headerRow, $label);
        }

        $headerRange = 'A'.$headerRow.':'.$lastColumn.$headerRow;
        $sheet->getStyle($headerRange)->getFont()->setBold(true);
        $sheet->getStyle($headerRange)->getFill()
            ->setFillType(Fill::FILL_SOLID)
            ->getStartColor()->setRGB('243C96');
        $sheet->getStyle($headerRange)->getFont()->getColor()->setRGB('FFFFFF');
        $sheet->getStyle($headerRange)->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER)
            ->setVertical(Alignment::VERTICAL_CENTER);

        $dataStart = $headerRow + 1;
        $currentRow = $dataStart;

        foreach ($rows as $row) {
            $this->writeTextCell($sheet, 'A'.$currentRow, (string) ($row['visit_id'] ?? ''));
            $this->writeTextCell($sheet, 'B'.$currentRow, (string) ($row['control_number'] ?? ''));
            $sheet->setCellValue('C'.$currentRow, (string) ($row['visitor_full_name'] ?? ''));

            if (($row['birth_date'] ?? null) instanceof Carbon) {
                $sheet->setCellValue('D'.$currentRow, ExcelDate::PHPToExcel($row['birth_date']));
                $sheet->getStyle('D'.$currentRow)->getNumberFormat()->setFormatCode('yyyy-mm-dd');
            } else {
                $sheet->setCellValue('D'.$currentRow, '');
            }

            $sheet->setCellValue('E'.$currentRow, (string) ($row['address'] ?? ''));
            $this->writeTextCell($sheet, 'F'.$currentRow, (string) ($row['contact_number'] ?? ''));
            $this->writeTextCell($sheet, 'G'.$currentRow, (string) ($row['pass_number'] ?? ''));
            $sheet->setCellValue('H'.$currentRow, (string) ($row['visit_type'] ?? ''));
            $sheet->setCellValue('I'.$currentRow, (string) ($row['purpose_of_visit'] ?? ''));
            $sheet->setCellValue('J'.$currentRow, (string) ($row['office_or_person'] ?? ''));

            if (($row['date_of_visit'] ?? null) instanceof Carbon) {
                $sheet->setCellValue('K'.$currentRow, ExcelDate::PHPToExcel($row['date_of_visit']));
                $sheet->getStyle('K'.$currentRow)->getNumberFormat()->setFormatCode('yyyy-mm-dd');
            } else {
                $sheet->setCellValue('K'.$currentRow, '');
            }

            if (($row['time_in'] ?? null) instanceof Carbon) {
                $sheet->setCellValue('L'.$currentRow, ExcelDate::PHPToExcel($row['time_in']));
                $sheet->getStyle('L'.$currentRow)->getNumberFormat()->setFormatCode('hh:mm:ss AM/PM');
            } else {
                $sheet->setCellValue('L'.$currentRow, '');
            }

            if (($row['time_out'] ?? null) instanceof Carbon) {
                $sheet->setCellValue('M'.$currentRow, ExcelDate::PHPToExcel($row['time_out']));
                $sheet->getStyle('M'.$currentRow)->getNumberFormat()->setFormatCode('hh:mm:ss AM/PM');
            } else {
                $sheet->setCellValue('M'.$currentRow, '');
            }

            $sheet->setCellValue('N'.$currentRow, (string) ($row['duration'] ?? ''));
            $sheet->setCellValue('O'.$currentRow, (string) ($row['visit_status'] ?? ''));
            $sheet->setCellValue('P'.$currentRow, (string) ($row['entry_method'] ?? ''));
            $sheet->setCellValue('Q'.$currentRow, (string) ($row['processed_by'] ?? ''));
            $sheet->setCellValue('R'.$currentRow, (string) ($row['alert'] ?? ''));
            $sheet->setCellValue('S'.$currentRow, (string) ($row['remarks'] ?? ''));

            $currentRow++;
        }

        $dataEnd = max($dataStart - 1, $currentRow - 1);
        $totalRow = $dataEnd + 2;
        $sheet->setCellValue('A'.$totalRow, 'Total Visitors:');
        $sheet->setCellValue('B'.$totalRow, $rows->count());
        $sheet->getStyle('A'.$totalRow.':B'.$totalRow)->getFont()->setBold(true);

        $sheet->setAutoFilter($headerRange);
        $sheet->freezePane('A'.($headerRow + 1));

        if ($dataEnd >= $headerRow) {
            $sheet->getStyle('A'.$headerRow.':'.$lastColumn.$dataEnd)->getBorders()->getAllBorders()
                ->setBorderStyle(Border::BORDER_THIN);
        }

        foreach (range('A', $lastColumn) as $column) {
            $sheet->getColumnDimension($column)->setAutoSize(true);
        }

        // Keep ID / contact / pass columns as text so leading zeros are preserved.
        $sheet->getStyle('A'.$dataStart.':A'.max($dataStart, $dataEnd))
            ->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_TEXT);
        $sheet->getStyle('B'.$dataStart.':B'.max($dataStart, $dataEnd))
            ->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_TEXT);
        $sheet->getStyle('F'.$dataStart.':F'.max($dataStart, $dataEnd))
            ->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_TEXT);
        $sheet->getStyle('G'.$dataStart.':G'.max($dataStart, $dataEnd))
            ->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_TEXT);
    }

    protected function writeExcelFile(Carbon $reportDate, Collection $rows, string $relativePath): string
    {
        $disk = Storage::disk(self::DISK);
        $directory = dirname($relativePath);

        if (! $disk->exists($directory) && ! $disk->makeDirectory($directory)) {
            throw new RuntimeException('Unable to create the secure report storage directory.');
        }

        $spreadsheet = $this->buildSpreadsheet($reportDate, $rows);
        $absolutePath = $disk->path($relativePath);

        $writer = new Xlsx($spreadsheet);
        $writer->save($absolutePath);
        $spreadsheet->disconnectWorksheets();
        unset($spreadsheet);

        return $absolutePath;
    }

    protected function writeDateRangeExcelFile(
        Carbon $startDate,
        Carbon $endDate,
        Collection $rows,
        string $relativePath,
        string $generatedByName
    ): string {
        $disk = Storage::disk(self::DISK);
        $directory = dirname($relativePath);

        if (! $disk->exists($directory) && ! $disk->makeDirectory($directory)) {
            throw new RuntimeException('Unable to create the secure report storage directory.');
        }

        $spreadsheet = $this->buildDateRangeSpreadsheet(
            $startDate,
            $endDate,
            $rows,
            $generatedByName,
            now('Asia/Manila')
        );
        $absolutePath = $disk->path($relativePath);

        $writer = new Xlsx($spreadsheet);
        $writer->save($absolutePath);
        $spreadsheet->disconnectWorksheets();
        unset($spreadsheet);

        return $absolutePath;
    }

    protected function writeTextCell(Worksheet $sheet, string $coordinate, string $value): void
    {
        $sheet->setCellValueExplicit($coordinate, $value, DataType::TYPE_STRING);
        $sheet->getStyle($coordinate)->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_TEXT);
    }

    protected function parseCalendarDate(string|\DateTimeInterface $date, string $label): Carbon
    {
        try {
            if ($date instanceof \DateTimeInterface) {
                return Carbon::instance(\DateTimeImmutable::createFromInterface($date))
                    ->timezone('Asia/Manila')
                    ->startOfDay();
            }

            $raw = trim((string) $date);
            $parsed = Carbon::createFromFormat('Y-m-d', $raw, 'Asia/Manila');

            if (! $parsed || $parsed->format('Y-m-d') !== $raw) {
                throw new RuntimeException('Please select a '.$label.'.');
            }

            return $parsed->startOfDay();
        } catch (RuntimeException $e) {
            throw $e;
        } catch (Throwable $e) {
            throw new RuntimeException('Please select a '.$label.'.');
        }
    }

    protected function sanitizeDateToken(string $dateString): string
    {
        if (! preg_match('/^\d{4}-\d{2}-\d{2}$/', $dateString)) {
            throw new RuntimeException('Invalid date token for report file naming.');
        }

        return $dateString;
    }

    protected function sanitizeFileName(string $fileName): string
    {
        $base = basename(str_replace(['\\', '/'], DIRECTORY_SEPARATOR, $fileName));
        $base = preg_replace('/[^A-Za-z0-9._-]/', '', $base) ?? '';

        if ($base === '' || ! str_ends_with(strtolower($base), '.xlsx')) {
            throw new RuntimeException('Invalid report file name.');
        }

        return $base;
    }

    protected function resolveAdminDisplayName(User|int|null $adminUser): string
    {
        if ($adminUser instanceof User) {
            $name = trim(((string) ($adminUser->first_name ?? '')).' '.((string) ($adminUser->last_name ?? '')));

            if ($name !== '') {
                return $name;
            }

            return (string) ($adminUser->email ?? 'Admin');
        }

        if ($adminUser === null) {
            return 'Admin';
        }

        $user = User::query()->find($adminUser);
        if (! $user) {
            return 'Admin #'.$adminUser;
        }

        return $this->resolveAdminDisplayName($user);
    }

    protected function formatAddress(array $visit): string
    {
        $line1 = trim(((string) ($visit['house_no'] ?? '')).' '.((string) ($visit['street'] ?? '')));

        return collect([
            $line1,
            $visit['barangay'] ?? null,
            $visit['city_municipality'] ?? null,
            $visit['province'] ?? null,
            $visit['region'] ?? null,
        ])->map(fn ($value) => trim((string) $value))
            ->filter(fn ($value) => $value !== '')
            ->implode(', ');
    }

    protected function resolveOfficeOrPerson(array $visit): string
    {
        $office = trim((string) ($visit['office_name'] ?? ''));
        $destination = trim((string) ($visit['destination_text'] ?? ''));
        $contactPerson = trim((string) ($visit['contractor_contact_person'] ?? ''));

        $parts = collect([$office, $destination, $contactPerson])
            ->filter(fn ($value) => $value !== '')
            ->unique()
            ->values();

        return $parts->implode(' / ');
    }

    protected function resolveVisitStatus(array $visit): string
    {
        $exitStatus = trim((string) ($visit['exit_status_name'] ?? ''));
        if ($exitStatus !== '') {
            return $exitStatus;
        }

        if (filled($visit['exit_time'] ?? null)) {
            return 'Completed';
        }

        return 'Active';
    }

    protected function resolveEntryMethod(array $visit): string
    {
        $roleId = (int) ($visit['guard_role_id'] ?? 0);
        if ($roleId === 4) {
            return 'Self-Registration';
        }

        $visitType = trim((string) ($visit['visit_type_name'] ?? ''));
        if ($visitType !== '') {
            return 'Guard Registration ('.$visitType.')';
        }

        return $roleId > 0 ? 'Guard Registration' : '';
    }

    protected function resolveDurationMinutes(array $visit, ?Carbon $entry, ?Carbon $exit): int
    {
        if (! $entry) {
            return 0;
        }

        if (! $exit) {
            return max(0, $entry->diffInMinutes(Carbon::now('Asia/Manila')));
        }

        $fromColumn = $visit['duration_minutes'] ?? null;
        if (is_numeric($fromColumn)) {
            return max(0, (int) $fromColumn);
        }

        return max(0, $entry->diffInMinutes($exit));
    }

    protected function formatDurationLabel(int $minutes): string
    {
        if ($minutes < 60) {
            return $minutes.' mins';
        }

        $hours = intdiv($minutes, 60);
        $remaining = $minutes % 60;

        if ($remaining === 0) {
            return $hours.' hr'.($hours > 1 ? 's' : '');
        }

        return $hours.' hr '.$remaining.' mins';
    }

    protected function parseDateTime(mixed $value): ?Carbon
    {
        if (! filled($value)) {
            return null;
        }

        try {
            return Carbon::parse($value)->timezone('Asia/Manila');
        } catch (Throwable $e) {
            return null;
        }
    }

    protected function parseDateOnly(mixed $value): ?Carbon
    {
        if (! filled($value)) {
            return null;
        }

        try {
            return Carbon::parse($value)->timezone('Asia/Manila')->startOfDay();
        } catch (Throwable $e) {
            return null;
        }
    }

    protected function safeErrorMessage(Throwable $e): string
    {
        $message = trim($e->getMessage());

        if ($message === '') {
            return 'Report generation failed due to an unexpected error.';
        }

        // Keep message user-safe; avoid dumping paths/credentials.
        $message = preg_replace('/[A-Za-z]:\\\\[^\s]+/', '[path]', $message) ?? $message;
        $message = preg_replace('/\/(?:var|home|Users|storage)[^\s]+/', '[path]', $message) ?? $message;

        return mb_substr($message, 0, 500);
    }
}
