@include('admin.partials.table-pagination-styles')
.alerts-summary-grid { grid-template-columns:repeat(2,minmax(0,1fr)); width:100%; }
.alerts-summary-card { display:flex; align-items:center; gap:22px; padding:22px; min-width:0; }
.alerts-summary-card.is-alert { background:linear-gradient(110deg,#fff,#fff5f5); }
.alerts-summary-card.is-completed { background:linear-gradient(110deg,#fff,#f0fdf8); }
.alerts-summary-card .summary-icon { width:76px; height:76px; border-radius:18px; font-size:32px; flex-shrink:0; }
.summary-copy { flex:1; min-width:0; }.summary-copy .summary-label { color:#10234c; font-weight:700; }.summary-number { margin:6px 0; font-size:36px; }.summary-text { margin:0; }
.alerts-panel-card { padding:20px; min-width:0; }.alerts-panel-header { gap:18px; flex-wrap:wrap; }.alerts-panel-actions { flex-wrap:wrap; gap:10px; }.alerts-panel-actions input { min-width:150px; width:190px; }.alerts-panel-actions select { max-width:180px; }
.alerts-list { padding:0; }.alerts-panel-title-wrap h3 { font-size:18px; }.alerts-panel-title-wrap p { font-size:13px; }
.completed-row { display:grid; grid-template-columns:1.5fr 1.5fr 1fr 1fr 1fr auto; gap:14px; align-items:center; padding:10px; border-bottom:1px solid #edf0f6; font-size:13px; color:#14274a; }
.completed-row > div { min-width:0; overflow-wrap:anywhere; }.completed-table-head { background:#f5f8fe; font-weight:700; font-size:12px; border-radius:8px 8px 0 0; }.completed-name { display:flex; align-items:center; gap:12px; }
.alert-avatar { width:42px;height:42px;flex-shrink:0;background:#e7efff;color:#0046c8;font-weight:700;border-radius:50%;display:flex;align-items:center;justify-content:center; }
.alert-action-btn { background:#0646bc; border:1px solid #0646bc; border-radius:8px; padding:10px 14px; font-size:13px; white-space:nowrap; cursor:pointer; text-decoration:none; }.guard-view-all { background:white; color:#0646bc; }
.alert-status-badge { white-space:nowrap; }.alert-status-badge.ready { background:#dcfce9; color:#087e46; }.alert-status-badge.unresolved { background:#ffe1e5; color:#d12135; }
.guard-alert-record { border:1px solid #f6cfd3;background:#fffbfc;border-radius:12px;margin-bottom:12px; overflow:hidden; }.guard-alert-top { display:flex;align-items:center;gap:16px;padding:16px; }.guard-alert-identity { flex:1;min-width:0; }.guard-alert-type { display:flex;align-items:center;gap:12px;flex-wrap:wrap; }.guard-alert-identity p { margin:4px 0 0;font-size:13px;color:#506080; }.guard-alert-time { display:flex;align-items:flex-end;flex-direction:column;gap:10px;font-size:12px;color:#506080; }
.severity-pill { display:inline-flex;padding:5px 12px;border-radius:8px;font-size:12px; }.severity-pill.severity-critical { background:#fee2e2;color:#b91c1c; }.severity-pill.severity-high { background:#ffedd5;color:#c2410c; }.severity-pill.severity-medium { background:#fef3c7;color:#92400e; }.severity-pill.severity-low { background:#dbeafe;color:#1d4ed8; }
.guard-alert-details { display:grid;grid-template-columns:1fr 1fr 2fr auto;align-items:center;gap:20px;padding:14px 16px;border-top:1px solid #f4e3e6;font-size:13px; }.guard-alert-details span { display:block;color:#65748d;font-size:12px;margin-bottom:8px; }.guard-alert-details strong { display:block; }.guard-alert-details p { margin:0;overflow-wrap:anywhere; }
.guard-list-overlay[hidden] { display:none; }.guard-list-overlay { position:fixed;inset:0;z-index:50;background:rgba(15,23,42,.5);display:flex;align-items:center;justify-content:center;padding:24px; }.guard-list-dialog { background:white;border-radius:16px;width:min(1200px,100%);max-height:calc(100dvh - 48px);display:flex;flex-direction:column;box-shadow:0 24px 80px #0f172a33; }.guard-list-header { display:flex;align-items:center;justify-content:space-between;padding:18px 22px;border-bottom:1px solid #e5e7eb; }.guard-list-header h2 { margin:0;font-size:20px;color:#12316a; }.guard-list-body { overflow:auto;padding:20px; }.guard-list-header button { border:0;background:#f1f5f9;border-radius:8px;width:40px;height:40px;font-size:24px;cursor:pointer; }.guard-list-filters { display:flex;gap:10px;flex-wrap:wrap;margin-bottom:16px; }.guard-list-error { color:#b91c1c;padding:10px; }.guard-list-loading { text-align:center;padding:32px;color:#506080; }
@media(max-width:1100px) { .completed-row { grid-template-columns:1.3fr 1.2fr 1fr 1fr 1fr auto;gap:8px; }.guard-alert-details { grid-template-columns:1fr 1fr; }.guard-alert-time { max-width:140px; } }
@media(max-width:700px) { .alerts-summary-grid { grid-template-columns:1fr; }.alerts-summary-card { gap:14px;padding:18px; }.alerts-summary-card .summary-icon { width:54px;height:54px;font-size:24px; }.alerts-panel-card { padding:14px; }.alerts-panel-actions { width:100%; }.alerts-panel-actions input,.alerts-panel-actions select { width:100%;max-width:none; }.completed-table-head { display:none; }.completed-row { grid-template-columns:1fr 1fr;gap:12px;padding:14px 0; }.completed-name { grid-column:1/-1; }.completed-row > div:not(.completed-name)::before { content:attr(data-label);display:block;font-size:11px;color:#65748d;margin-bottom:5px; }.guard-alert-top { flex-wrap:wrap;gap:10px; }.guard-alert-time { flex-direction:row;align-items:center;max-width:none;width:100%;justify-content:space-between; }.guard-alert-details { grid-template-columns:1fr;gap:12px; }.guard-list-overlay { padding:10px; }.guard-list-dialog { max-height:calc(100dvh - 20px); }.guard-list-body { padding:14px; }.guard-list-filters > * { width:100%; }.alert-action-btn { min-height:42px; }.summary-copy .summary-label { font-size:14px; } }

.guard-visitor-photo { width:42px;height:42px;object-fit:cover;border-radius:50%;flex-shrink:0; }.alert-avatar[hidden],.guard-visitor-photo[hidden] { display:none; }
