@php $activeNav = 'reports'; @endphp
@extends('office.layouts.office-layout')

@section('title', 'Daily Reports')

@section('content')
<div class="office-card mb-3">
	<div class="d-flex flex-wrap justify-content-between align-items-start gap-2 mb-3">
		<div>
			<h2>Daily Reports</h2>
			<p class="card-muted mb-0">Daily visitor Excel reports for {{ $office->office_name }}</p>
		</div>
		<button type="button" class="btn btn-nu-primary" data-bs-toggle="modal" data-bs-target="#generateReportModal">
			<i class="bi bi-plus-circle me-1"></i> Generate Daily Report
		</button>
	</div>

	@if (session('success'))
		<div class="alert alert-success alert-dismissible fade show" role="alert">
			{{ session('success') }}
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
	@endif

	@if (session('error'))
		<div class="alert alert-danger alert-dismissible fade show" role="alert">
			{{ session('error') }}
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
	@endif

	@if ($errors->any())
		<div class="alert alert-danger alert-dismissible fade show" role="alert">
			<ul class="mb-0 ps-3">
				@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
				@endforeach
			</ul>
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
	@endif

	<form method="GET" action="{{ route('office.daily-reports') }}" class="row g-2 align-items-end">
		<div class="col-md-3">
			<label for="report_date" class="form-label fw-semibold">Report Date</label>
			<input type="date" id="report_date" name="report_date" class="form-control" max="{{ $maxDate }}" value="{{ $filters['report_date'] }}">
		</div>
		<div class="col-md-3">
			<label for="date_from" class="form-label fw-semibold">Date From</label>
			<input type="date" id="date_from" name="date_from" class="form-control" max="{{ $maxDate }}" value="{{ $filters['date_from'] }}">
		</div>
		<div class="col-md-3">
			<label for="date_to" class="form-label fw-semibold">Date To</label>
			<input type="date" id="date_to" name="date_to" class="form-control" max="{{ $maxDate }}" value="{{ $filters['date_to'] }}">
		</div>
		<div class="col-md-3 d-flex gap-2">
			<button type="submit" class="btn btn-nu-primary flex-grow-1">
				<i class="bi bi-search me-1"></i> Search
			</button>
			<a href="{{ route('office.daily-reports') }}" class="btn btn-nu-outline">Reset</a>
		</div>
	</form>
</div>

<div class="office-card">
	@if ($reports->isEmpty())
		<div class="empty-state">
			<i class="bi bi-folder2-open" aria-hidden="true"></i>
			<p class="mb-2 fw-semibold">No daily reports found</p>
			<p class="mb-3 card-muted">Missing reports are auto-filled when you open this page. Generate a report for any past date as needed.</p>
			<button type="button" class="btn btn-nu-primary" data-bs-toggle="modal" data-bs-target="#generateReportModal">
				Generate Daily Report
			</button>
		</div>
	@else
		<div class="table-scroll">
			<table class="table-office">
				<thead>
					<tr>
						<th>Report Date</th>
						<th>File Name</th>
						<th>Visitor Records</th>
						<th>Status</th>
						<th>Generated At</th>
						<th>Generated By</th>
						<th>Actions</th>
					</tr>
				</thead>
				<tbody>
					@foreach ($reports as $report)
						@php
							$generator = $report->generator;
							$generatorName = $generator
								? trim(((string) ($generator->first_name ?? '')).' '.((string) ($generator->last_name ?? '')))
								: '';
							if ($generatorName === '' && $generator) {
								$generatorName = (string) ($generator->email ?? '');
							}
							if ($generatorName === '') {
								$generatorName = $report->generated_by ? 'User #'.$report->generated_by : 'System';
							}
							$statusClass = match ($report->generation_status) {
								'completed' => 'report-status-completed',
								'failed' => 'report-status-failed',
								'generating' => 'report-status-generating',
								default => 'report-status-pending',
							};
						@endphp
						<tr>
							<td>{{ optional($report->report_date)->format('M d, Y') }}</td>
							<td><code>{{ $report->file_name }}</code></td>
							<td>{{ number_format((int) $report->record_count) }}</td>
							<td>
								<span class="report-status-badge {{ $statusClass }}">
									{{ ucfirst($report->generation_status) }}
								</span>
								@if ($report->generation_status === 'failed' && $report->error_message)
									<div class="small text-danger mt-1">{{ \Illuminate\Support\Str::limit($report->error_message, 80) }}</div>
								@endif
							</td>
							<td>
								{{ $report->generated_at ? $report->generated_at->timezone('Asia/Manila')->format('M d, Y h:i A') : '—' }}
							</td>
							<td>{{ $generatorName }}</td>
							<td>
								<div class="d-flex flex-wrap gap-1">
									@if ($report->isDownloadable())
										<a href="{{ route('office.daily-reports.download', $report->id) }}" class="btn btn-sm btn-success">
											<i class="bi bi-download"></i> Download
										</a>
									@else
										<button type="button" class="btn btn-sm btn-outline-secondary" disabled title="Report is not ready for download">
											<i class="bi bi-download"></i> Download
										</button>
									@endif

									<button
										type="button"
										class="btn btn-sm btn-nu-outline"
										data-bs-toggle="modal"
										data-bs-target="#regenerateModal{{ $report->id }}"
									>
										<i class="bi bi-arrow-repeat"></i> Regenerate
									</button>
								</div>

								<div class="modal fade" id="regenerateModal{{ $report->id }}" tabindex="-1" aria-hidden="true">
									<div class="modal-dialog">
										<form method="POST" action="{{ route('office.daily-reports.regenerate', $report->id) }}" class="modal-content">
											@csrf
											<div class="modal-header">
												<h5 class="modal-title">Regenerate Report</h5>
												<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
											</div>
											<div class="modal-body">
												<p class="mb-2">
													This will replace the existing Excel file for
													<strong>{{ optional($report->report_date)->format('M d, Y') }}</strong>
													using the latest visitor data for {{ $office->office_name }}.
												</p>
												<div class="form-check">
													<input class="form-check-input" type="checkbox" value="1" id="confirm{{ $report->id }}" name="confirm" required>
													<label class="form-check-label" for="confirm{{ $report->id }}">
														I confirm I want to replace the existing report.
													</label>
												</div>
											</div>
											<div class="modal-footer">
												<button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
												<button type="submit" class="btn btn-nu-primary">Regenerate Report</button>
											</div>
										</form>
									</div>
								</div>
							</td>
						</tr>
					@endforeach
				</tbody>
			</table>
		</div>

		@include('admin.partials.table-pagination', [
			'paginator' => $reports,
			'perPageParam' => 'per_page',
			'ariaLabel' => 'Daily reports pagination',
		])
	@endif
</div>

<div class="modal fade" id="generateReportModal" tabindex="-1" aria-labelledby="generateReportModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<form method="POST" action="{{ route('office.daily-reports.generate') }}" class="modal-content" id="generateReportForm">
			@csrf
			<div class="modal-header">
				<h5 class="modal-title" id="generateReportModalLabel">Generate Daily Report</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<label class="form-label fw-semibold" for="generate_report_date">Select Report Date</label>
				<input
					type="date"
					id="generate_report_date"
					name="report_date"
					class="form-control"
					max="{{ $maxDate }}"
					value="{{ old('report_date', $maxDate) }}"
					required
				>
				<p class="small text-muted mt-2 mb-0">
					Future dates are not allowed. The report includes visitors scanned at {{ $office->office_name }} on the selected date.
				</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
				<button type="submit" class="btn btn-nu-primary" id="generateReportSubmit">
					<span class="generate-label">Generate Report</span>
					<span class="generate-loading d-none">
						<span class="spinner-border spinner-border-sm me-1" role="status" aria-hidden="true"></span>
						Generating...
					</span>
				</button>
			</div>
		</form>
	</div>
</div>
@endsection

@push('styles')
<style nonce="{{ $cspNonce }}">
	@include('admin.partials.table-pagination-styles')

	.report-status-badge {
		display: inline-flex;
		align-items: center;
		padding: 4px 10px;
		border-radius: 999px;
		font-size: 12px;
		font-weight: 700;
	}

	.report-status-completed { background: #dcfce7; color: #166534; }
	.report-status-failed { background: #fee2e2; color: #991b1b; }
	.report-status-generating { background: #dbeafe; color: #1e40af; }
	.report-status-pending { background: #f1f5f9; color: #475569; }
</style>
@endpush

@push('scripts')
<script nonce="{{ $cspNonce }}">
	@include('admin.partials.table-pagination-script')

	(function () {
		const form = document.getElementById('generateReportForm');
		const submitBtn = document.getElementById('generateReportSubmit');
		if (form && submitBtn) {
			form.addEventListener('submit', function () {
				submitBtn.disabled = true;
				submitBtn.querySelector('.generate-label')?.classList.add('d-none');
				submitBtn.querySelector('.generate-loading')?.classList.remove('d-none');
			});
		}
	})();
</script>
@endpush
