<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;
use Illuminate\View\View;

class AuthController extends Controller
{
    public function showLogin(): View|RedirectResponse
    {
        if (Auth::check()) {
            return $this->redirectByRole((int) Auth::user()->role_id);
        }

        return view('welcome');
    }

    public function login(Request $request): RedirectResponse
    {
        $credentials = $request->validate([
            'email' => ['required', 'email'],
            'password' => ['required', 'string'],
        ]);

        $user = User::query()->where('email', $credentials['email'])->first();

        if (! $user || ! is_string($user->password_hash) || ! $this->isValidPassword($user, $credentials['password'])) {
            throw ValidationException::withMessages([
                'email' => 'Invalid email or password.',
            ]);
        }

        Auth::login($user);

        $request->session()->regenerate();

        $roleId = (int) $user->role_id;

        if (! in_array($roleId, [1, 2], true)) {
            Auth::logout();
            $request->session()->invalidate();
            $request->session()->regenerateToken();

            throw ValidationException::withMessages([
                'email' => 'This account is not allowed in the web app.',
            ]);
        }

        return $this->redirectByRole($roleId);
    }

    public function logout(Request $request): RedirectResponse
    {
        Auth::logout();

        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect()->route('login');
    }

    private function redirectByRole(int $roleId): RedirectResponse
    {
        if ($roleId === 1) {
            return redirect()->to('/admin/dashboard');
        }

        return redirect()->to('/guard/dashboard');
    }

    private function isValidPassword(User $user, string $inputPassword): bool
    {
        $stored = (string) $user->password_hash;

        // Bcrypt/argon hashes generated by password_hash() use this format.
        if (str_starts_with($stored, '$')) {
            return password_verify($inputPassword, $stored);
        }

        // Backward compatibility for plain-text seeded/demo records.
        if (! hash_equals($stored, $inputPassword)) {
            return false;
        }

        // Upgrade plain-text password to hashed value after successful login.
        $user->password_hash = Hash::make($inputPassword);
        $user->save();

        return true;
    }
}
